name: Pull Request Opened Event
on:
  pull_request:
    types: 
     - opened
    branches:
     - main
jobs:
  Build-triggers:
    runs-on: windows-latest
    steps:
      - name: first step
        run: echo "windows-platform"
