name: Deployment Event Workflow

on:
 deployment:
  types: [created, updated]
  environments: 
   - production
   - staging

jobs:
  deployment-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print deployment details
        run: |
          echo "Deployment event type: ${{ github.event.action }}"
          echo "Deployment environment: ${{ github.event.deployment.environment }}"
          echo "Deployment status: ${{ github.event.deployment.status }}"
