name: Deployment Event Workflow

# Trigger the workflow when a deployment is created
on:
  deployment:
    types:
      - created  # Trigger when a deployment is created

jobs:
  deployment:
    runs-on: ubuntu-latest  # The job will run on the latest Ubuntu environment
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout code

      - name: Deployment triggered by event
        run: |
          echo "Deployment event triggered!"
          echo "You can run deployment tasks here, e.g., SSH or API calls."
          
      - name: Notify team (optional)
        run: |
          echo "Sending notifications about deployment..."
          # You can use Slack, email, or other services for notifications here.
