name: First workflow
run-name: First workflow in github actions
on:
 discussion:
  types: created
jobs:
  echo-build:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "First Workflow"
