name: run job on different environments
run-name: environments
on:
 push:
jobs:
  Dev_job: 
   runs-on: ubuntu-latest
   environment: DEV
   steps:
    - uses: actions/checkout@v1
    - name: run scripts
      run: |
       echo "I am running a job in Development"
       echo "printing secrect ${{ secrets.mysecret }}"
