name: Trigger workflow- windows
run-name: this workflow will run on windows server
on:
  push
jobs:
  echo-triggers:
    runs-on: windows-latest
    steps:
      - name: first step
        run: echo "windows-platform"
